name: Feature Request
description: Suggest an idea or enhancement for Muse
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - ''
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an idea to improve Muse!
  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. "I'm always frustrated when..."
    validations:
      required: false # Encouraged, but not strictly required
  - type: textarea
    id: desired-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered (Optional)
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context (Optional)
      description: Add any other context or screenshots about the feature request here. Why is this important? Who would benefit?
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting, please ensure you've done the following.
      options:
        - label: I have searched the existing issues and confirmed this is not a duplicate suggestion.
          required: true
        - label: I have read the [CONTRIBUTING.md](https://github.com/plaid-ai/muse/blob/main/CONTRIBUTING.md) guide.
          required: true